services:
  mongo:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - rayltics-net

  api-gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
      target: runner
      args:
        APP_NAME: api-gateway
    ports:
      - '${GATEWAY_PORT}:3000'
    environment:
      - PORT=${GATEWAY_PORT}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - MATH_SERVICE_URL=${MATH_SERVICE_URL}
      - MONGO_URI=${MONGO_URI}
    networks:
      - rayltics-net

  auth-service:
    build:
      context: .
      dockerfile: services/Dockerfile
      target: runner
      args:
        APP_NAME: auth-service
    ports:
      - '${AUTH_PORT}:3333'
    environment:
      - PORT=${AUTH_PORT}
      - MONGO_URI=${AUTH_MATH_MONGO_URI}
    networks:
      - rayltics-net

volumes:
  mongo_data:

networks:
  rayltics-net:
    driver: bridge
