services:
  mongo:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - rayltics-net

  api-gateway:
    build:
      context: ../../
      dockerfile: infra/docker/gateway/Dockerfile
      target: dev
      args:
        APP_NAME: api-gateway
    command: npx nodemon --legacy-watch --watch apps/api-gateway/src --ext ts,json --exec "npx nx build api-gateway && node apps/api-gateway/dist/main.js"
    ports:
      - '${GATEWAY_PORT}:3000'
    environment:
      - PORT=${GATEWAY_PORT}
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
    volumes:
      - ../../:/app
      - /app/node_modules
    depends_on:
      - auth-service
    networks:
      - rayltics-net

  auth-service:
    build:
      context: ../../
      dockerfile: infra/docker/services/Dockerfile
      target: dev
      args:
        APP_PORT: ${AUTH_PORT}
        APP_NAME: auth
    command: npx nodemon --legacy-watch --watch apps/services/auth/src --ext ts,json --exec "npx nx build auth && node apps/services/auth/dist/main.js"
    ports:
      - '${AUTH_PORT}:3333'
      - '9230:9229'
    environment:
      - PORT=${AUTH_PORT}
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NODE_PATH=/node_modules
      - MONGO_URI=${AUTH_MONGO_URI}
    volumes:
      - ../../:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - rayltics-net

volumes:
  mongo_data:

networks:
  rayltics-net:
    driver: bridge
